BEGIN;
	CREATE TABLE
	IF
		NOT EXISTS `user` (
			`id` BIGINT ( 20 ) NOT NULL AUTO_INCREMENT COMMENT '主键',
			`nickName` VARCHAR ( 128 ) NOT NULL DEFAULT '' COMMENT '昵称',
			`loginName` VARCHAR ( 128 ) NOT NULL COMMENT '登陆名',
			`password` VARCHAR ( 128 ) NOT NULL COMMENT '登陆密码',
			`money` DECIMAL ( 20, 10 ) NOT NULL DEFAULT 0 COMMENT '余额',
			`dbctime` DATETIME ( 3 ) DEFAULT CURRENT_TIMESTAMP ( 3 ) COMMENT '创建时间',
			`dbutime` DATETIME ( 3 ) DEFAULT CURRENT_TIMESTAMP ( 3 ) ON UPDATE CURRENT_TIMESTAMP ( 3 ) COMMENT '更新时间',
			PRIMARY KEY ( `id` ) 
		) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT '用户';
	CREATE TABLE
	IF
		NOT EXISTS `product` (
			`id` BIGINT ( 20 ) NOT NULL AUTO_INCREMENT COMMENT '主键',
			`name` VARCHAR ( 128 ) NOT NULL DEFAULT '' COMMENT '名字',
			`price` DECIMAL ( 10, 5 ) NOT NULL COMMENT '单价',
			`stock` BIGINT ( 20 ) NOT NULL DEFAULT 0 COMMENT '库存',
			`dbctime` DATETIME ( 3 ) DEFAULT CURRENT_TIMESTAMP ( 3 ) COMMENT '创建时间',
			`dbutime` DATETIME ( 3 ) DEFAULT CURRENT_TIMESTAMP ( 3 ) ON UPDATE CURRENT_TIMESTAMP ( 3 ) COMMENT '更新时间',
			PRIMARY KEY ( `id` ) 
		) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT '商品';
	CREATE TABLE
	IF
		NOT EXISTS `order` (
			`id` BIGINT ( 20 ) NOT NULL AUTO_INCREMENT COMMENT '主键',
			`price` DECIMAL ( 10, 5 ) NOT NULL COMMENT '订单价格',
			`status` TINYINT ( 4 ) NOT NULL COMMENT '状态: 0新建 1已支付 2已过期',
			`userId` BIGINT ( 20 ) NOT NULL DEFAULT 0 COMMENT '用户id',
			`productId` BIGINT ( 20 ) NOT NULL DEFAULT 0 COMMENT '商品id',
			`dbctime` DATETIME ( 3 ) DEFAULT CURRENT_TIMESTAMP ( 3 ) COMMENT '创建时间',
			`dbutime` DATETIME ( 3 ) DEFAULT CURRENT_TIMESTAMP ( 3 ) ON UPDATE CURRENT_TIMESTAMP ( 3 ) COMMENT '更新时间',
			PRIMARY KEY ( `id` ) 
		) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT '商品';
COMMIT;